[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "capycafe"
version = "1.2.0"
description = "Информационная система для кафе"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Гусаров А.С." },
    { name = "Покусаев И.А." }
]
keywords = ["sqlite3", "console", "cafe-management", "practice"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
]

# Зависимости, необходимые для сборки исполняемого .exe пакета
dependencies = [
    "pyinstaller>=6.0.0"
]

[tool.setuptools]
packages = ["main", "database"]
